## -*- encoding: utf-8 -*-
## This file (troubleshooting.sagetex.sage) was *autogenerated* from troubleshooting.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('troubleshooting', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
